# Generated by Django 3.2.12 on 2023-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230929_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='name', max_length=10),
        ),
    ]
