# Generated by Django 3.2.12 on 2023-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profilemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='name', max_length=10, null=True),
        ),
    ]
