# Generated by Django 3.2.12 on 2023-09-29 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_profilemodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
