# Generated by Django 3.2.12 on 2023-09-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230929_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='check',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='name', max_length=10, null=True),
        ),
    ]
